name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.17
   
    - name: Install dependencies
      run: |
        cd Backend
        make install
    - name: Format code with Python black
      run: |
        cd Backend
        make format
    - name: Lint 
      run: |
        cd backend
        make lint
    - name: Test with pytest
      run: |
        cd Backend
        make test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Node.js dependencies
      run: |
        cd Frontend
        cd simulation_app
        npm install
    - name: Check Node.js and npm version
      run: |
        cd Frontend
        node -v
        npm -v
    - name: Test with npm
      run: |
        cd Frontend
        cd simulation_app
        npm test
    - name: Lint with ESLint
      run: |
        cd Frontend
        cd simulation_app
        npx eslint .
    - name: Format with Prettier
      run: |
        cd Frontend
        cd simulation_app
        npx prettier --write .
        npx prettier --check .
